### ISSUE TITLE
Notification implementation

### ISSUE THREAD

**Issue by aiinkiestism** [dao-to-earth/d2d-deal-v1#50]
- Notification icon(UI) and its logic
- Notificaiton in EPNS

**Comment by Willgg** [comment]
tbh I don't understand why we need this feature. When 2 DAOs will have to deal they (members actually) will talk to each other through discord, snapshot or whatever. They don't need a notification to know that a deal has been accepted. You don't rely on notifications when it is about big money.

**Comment by eugenPtr** [comment]
> tbh I don't understand why we need this feature. When 2 DAOs will have to deal they (members actually) will talk to each other through discord, snapshot or whatever. They don't need a notification to know that a deal has been accepted. You don't rely on notifications when it is about big money.

I agree the DAOs will probably let each other know about the status of the deal. 
Let's leave this for now and think about it only if the users will specifically ask for this feature

**Comment by aiinkiestism** [comment]
You guys are right maybe, it's not a must and needed feature at all.
